"""
Django settings for SchoolHub project.

Generated by 'django-admin startproject' using Django 5.1.4.
"""

from pathlib import Path
from decouple import config
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']  # السماح بجميع الهوستات أثناء التطوير

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django_crontab',  # لإعداد النسخ الاحتياطي اليومي باستخدام cron
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'teachers',
    'students',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SchoolHub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SchoolHub.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'schoolhub_db',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Tell Django to use your custom user model
AUTH_USER_MODEL = 'accounts.User'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Baghdad'  # أو أي منطقة زمنية تريدها
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Media files (user uploaded content)
MEDIA_URL = '/media/'  # تأكد من أن المسار يبدأ بـ /
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Authentication URLs
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

MESSAGE_TAGS = {messages.ERROR: "danger"}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# إعدادات django-fernet-fields لتشفير الحقول الحساسة
# تأكد من إضافة FERNET_KEY في ملف .env الخاص بالمشروع
FERNET_KEYS = [
    config('FERNET_KEY')
]

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "SchoolHub Admin",
    "site_header": "SchoolHub Admin",
    "site_brand": "SchoolHub",
    "site_logo": "assets/images/school.jpg",
    "site_icon": "assets/images/favicon.ico",
    "welcome_sign": "Welcome to SchoolHub, your comprehensive school management system!",
    "copyright": " SchoolHub. Designed by Hawraa AbdulRazzaq",
    "user_avatar": "avatar",
    "order_with_respect_to": [
        "dashboard",
        "students",
        "teachers",
        "classes",
        "attendance",
    ],
    "icons": {
        "admin.LogEntry": "fas fa-history",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "students": "fas fa-user-graduate",
        "teachers": "fas fa-chalkboard-teacher",
        "classes": "fas fa-school",
        "attendance": "fas fa-calendar-check",
    },
    "show_ui_builder": True,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.user"},
        {"app": "students"},
        {"app": "teachers"},
    ],
    "custom_css": ["assets/css/custom_admin.css"],
    "custom_js": ["assets/js/custom_admin.js"],
}

JJAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-orange",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-orange",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "materia",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info btn-gradient",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success btn-glow"
    },
    "sidebar_scrollable": True,
    "body_bg": "#f0f8ff",
    "navbar_bg": "#d0e7ff",
    "footer_bg": "#d0e7ff",
    "sidebar_bg": "#b0d4f1",
    "card_bg": "#FFFFFF",
    "card_body_classes": "p-4 rounded-3 shadow-sm bg-light",
    "form_classes": "form-control-lg shadow-sm rounded-pill",
    "input_classes": "input-lg rounded shadow-sm",
    "shadow_classes": "shadow-lg glow-effect",
    "hover_effects": True,
    "rounded_corners": True,
    "gradient_borders": True,
    "actions_sticky_top": False,
    "navbar_link_color": "#ff6600",
    "navbar_link_hover_color": "#ff3300"
}

# إعداد مهمة النسخ الاحتياطي اليومي باستخدام django-crontab
# سيتم تشغيل أمر النسخ الاحتياطي (backup_students) يومياً عند الساعة 2 صباحاً
CRONJOBS = [
    ('0 2 * * *', 'django.core.management.call_command', ['backup_students']),
]

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1_000_000
