# Generated by Django 5.1.5 on 2025-04-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reports Dashboard',
                'verbose_name_plural': 'Reports Dashboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personal', 'Personal Information Report'), ('guardian', 'Guardian Information Report'), ('health', 'Health Information Report'), ('academic', 'Academic Information Report')], default='personal', help_text='Report category (Personal, Guardian, Health, Academic).', max_length=20)),
                ('report_type', models.CharField(default='Automatic', help_text='Type or classification of the report.', max_length=50)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='New', help_text='Current status of the report.', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the report was generated.')),
                ('data', models.JSONField(help_text='Additional report data in a flexible JSON format.')),
            ],
        ),
    ]
