# Generated by Django 5.1.5 on 2025-03-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(help_text='The student to whom this report belongs.', on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
