# Generated by Django 5.1.5 on 2025-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_at']},
        ),
    ]
